### ISSUE TITLE
How to fill screen without `backgroundLayer.fillScreen()` ? Getting `Not Implemented in Framebuffer::GFX`.

### ISSUE THREAD

**Issue by GeorgeFlorian** [marcmerlin/Framebuffer_GFX#1]
Board: ESP32  
Platform: PlatformIO

**Using SmartMatrix.** (or trying to use)

I have tried filling the screen with a color using:
```
#define LED_RED_HIGH 		  (31 << 11)
matrix->drawRect(0, 0, kMatrixWidth, kMatrixHeight, LED_RED_HIGH);
matrix->fillRect(0, 0, kMatrixWidth, kMatrixHeight, LED_RED_HIGH);
// or
matrix->fillScreen(LED_RED_HIGH);
```
and in both cases I get:
```
Not Implemented in Framebuffer::GFX
```

How are these not implemented ??? How do I fill the screen with a color without using `backgroundLayer.fillScreen()` ?

**Comment by GeorgeFlorian** [comment]
This is the whole function:
```
    if(current_demo == "Demo_1") {
      // light all leds at once at an entered brightness;
      matrix->clear();
      matrix->setBrightness(brightness.toInt());
      // matrix->drawRect(0, 0, kMatrixWidth, kMatrixHeight, getColor(color));
      // matrix->fillRect(0, 0, kMatrixWidth, kMatrixHeight, getColor(color));
      backgroundLayer.fillScreen( {0x00,0xFF,0xFF} );
    }
```

Even this returns `Not Implemented in Framebuffer::GFX`. I can't figure out what is happening.

**Comment by GeorgeFlorian** [comment]
Apparently I had problems with `matrix->setBrightness(brightness.toInt());` because these libraries got over complicated with time and I have no idea which function works for what layer.

For now this fixed my issue:
```
matrixLayer.setBrightness(brightness.toInt());
```

**Comment by marcmerlin** [comment]
Hi, generally it really helps if you post your whole code online (gist.github.com if you have nothing else).
I'm not sure which library you're trying to use, but I'll assume you're actually using SmartMatrix::GFX?

In your case, grep would have helped:
https://github.com/marcmerlin/Framebuffer_GFX/blob/master/Framebuffer_GFX.h#L114
there is even a comment that tells you what to do
  // For SmartMatrix, brightness is done outside this object

So, your error is not with fillscreen but with setbrightness
https://github.com/marcmerlin/FastLED_NeoMatrix_SmartMatrix_LEDMatrix_GFX_Demos/blob/fc4a221d392211e69ba1137ce04edaeceb855a07/neomatrix_config.h#L1033
gives you an example
matrixLayer is where to set this

**Comment by marcmerlin** [comment]
ok, just spent time writing this up for nothing :)
There may be issues in my code, I'm sure there are bugs, but please spend a little time looking around (grep made this trivial) before filing an issue :)

**Comment by marcmerlin** [comment]
and just in case you wonder why it's that way, it's because smartmatrix uses 2 different objects, and brightness is kept in a different one that isn't passed to framebuffer::gfx, so it has no access to that other object and no way to set a callback to it for brightness.
